// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzPOqQjHxdPbmPeL-9X6i0MYnE6Ey4BQ',
    appId: '1:857969369027:web:8666f7e766be5343576776',
    messagingSenderId: '857969369027',
    projectId: 'minimsgapp-f07b0',
    authDomain: 'minimsgapp-f07b0.firebaseapp.com',
    storageBucket: 'minimsgapp-f07b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Lmb-StfWq2e70Q-LdNCQD9Axfaf0cvc',
    appId: '1:857969369027:android:ef1333bb3478de39576776',
    messagingSenderId: '857969369027',
    projectId: 'minimsgapp-f07b0',
    storageBucket: 'minimsgapp-f07b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDimnvJ7LZvdib2dUetol9nnZCntabnwvA',
    appId: '1:857969369027:ios:4d9da321ecdd0cfc576776',
    messagingSenderId: '857969369027',
    projectId: 'minimsgapp-f07b0',
    storageBucket: 'minimsgapp-f07b0.appspot.com',
    iosBundleId: 'com.example.minimsgappPantaleta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDimnvJ7LZvdib2dUetol9nnZCntabnwvA',
    appId: '1:857969369027:ios:4d9da321ecdd0cfc576776',
    messagingSenderId: '857969369027',
    projectId: 'minimsgapp-f07b0',
    storageBucket: 'minimsgapp-f07b0.appspot.com',
    iosBundleId: 'com.example.minimsgappPantaleta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGzPOqQjHxdPbmPeL-9X6i0MYnE6Ey4BQ',
    appId: '1:857969369027:web:8b8ab87a622d3cd8576776',
    messagingSenderId: '857969369027',
    projectId: 'minimsgapp-f07b0',
    authDomain: 'minimsgapp-f07b0.firebaseapp.com',
    storageBucket: 'minimsgapp-f07b0.appspot.com',
  );
}
